site_name: Rust Project Deliverable 1
site_url: http://127.0.0.1:8000/

nav:
    - Home: index.md
    - Class List: classlist.md
    - Class Index: classindex.md
    - Class Hierarchy: hierarchy.md
    - Class Members: members.md
  
theme: "readthedocs"

plugins:
  - mkdocstrings
  - mermaid2

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid2
          class: mermaid2
          format: !!python/name:pymdownx.superfences.fence_code_format


